# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/colonel_blotto',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/colonel_blotto',
                'lib_path': 'colonel_blotto'},
  'syms': {'colonel_blotto.core': {'colonel_blotto.core.foo': ('core.html#foo', 'colonel_blotto/core.py')}}}